### ISSUE TITLE
Rendern von Stichpunkten

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/Protokollfix#1]
Stichpunkte, die im Markdown korrekt angegeben und auch in der Live-Vorschau korrekt gerendert werden, erscheinen im generierten PDF ohne die gewünschte Formatierung.

vgl. https://geofs.uni-muenster.de/wp/wp-content/uploads/protokolle/2016/2016_11_09_FSR-Sitzung.md vs. https://geofs.uni-muenster.de/wp/wp-content/uploads/protokolle/2016/2016_11_09_FSR-Sitzung.pdf

**Comment by noerw** [comment]
for future reference:
https://talk.commonmark.org/t/requiring-a-blank-line-between-a-paragraph-and-list/657/23

**Comment by christophfriedrich** [comment]
🙄 
Dann die Live-Vorschau so anpassen, dass sie dem PDF-Export entspricht? Ich vermute, das würde man erreichen, indem man die kramed-Option smartLists auf false setzt?
