### ISSUE TITLE
Documents only published on first save

### ISSUE THREAD

**Issue by SpeckiJ** [fs-geofs/Protokollfix#12]
The pdf Document published on the website is only generated when save() is clicked for the first time.
Any subsequent Saves are ignored.

This leads to problems if you saved the Document before finishing it.

**Comment by noerw** [comment]
Are you sure? [The code exports unconditionally](https://github.com/fs-geofs/Protokollfix/blob/master/lib/routesAPI.js#L26-L32).
Or are you talking about the offered download, not the export update?

**Comment by SpeckiJ** [comment]
The Server responds with a `500 Internal Server Error` on every request to `/save` after the initial save.

**Comment by noerw** [comment]
can't reproduce locally, will try in production and probably spam the protokolle folder shortly ;)

**Comment by noerw** [comment]
problem was that we had old version of node installed, v8.5 is required since last patches
