### ISSUE TITLE
Saving the finished document overwrites template?

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/Protokollfix#14]
I've observed that navigating to `geofs/protokolle` forwards to `geofs/protokolle/template/FSR-Sitzung.md`, but the document that then pre-populates the editor isn't a template, but the latest Protokoll.

I checked on the server and saw that the file `data/templates/FSR-Sitzung.md` indeed contains the contents of the last Protokoll (i.e. it's identical to `data/documents/2020_04_01_FSR-Sitzung.md`). A look at the modification date confirmed my assumption that on the most recent save, the template was overwritten with what was in the editor at that time.

Is that the supposed behaviour??

**Comment by christophfriedrich** [comment]
Maybe an unwanted, undiscovered side-effect of https://github.com/fs-geofs/Protokollfix/pull/8/commits/6b3251c73f2906e446a5f7d1ea364d9bbcf035d7 ?

**Comment by noerw** [comment]
This is intended behaviour, as the template otherwise would get outdated quickly.
I implemented in https://github.com/fs-geofs/Protokollfix/commit/f90c676613461df8a5b0052821f7e688d0d7120d as part of me leaving behind IT maintenance tasks like this

**Comment by christophfriedrich** [comment]
Then the "template" is now no longer what I would call a template, but the behaviour itself is probably desirable because as you wrote in the commit message there it "eases some tasks". So all good, I was just confused.
