### ISSUE TITLE
Yaml header missing in PDF

### ISSUE THREAD

**Issue by christophfriedrich** [fs-geofs/Protokollfix#16]
The [25 September of last year](https://geofs.uni-muenster.de/wp/wp-content/uploads/protokolle/2019/2019_09_25_FSR-Sitzung.pdf) is the last protocol that has a correct heading. Since [16 October](https://geofs.uni-muenster.de/wp/wp-content/uploads/protokolle/2019/2019_10_16_FSR-Sitzung.pdf) it's missing. The markdown files look identical, so I think it's not a user error.

I assume the yaml header is not parsed (correctly)? 🤔 

But there's no commit that was done between 25.9. and 16.10., so the sudden change is weird. Or was 01ef48ca7e2438f9e6d54ad979fb5a5981c327f7 only deployed later and that change caused it?

**Comment by noerw** [comment]
The problem is in fact in the documents, the yaml header is malformed:

is:
```
---
date: 29.04.2020, 18:07:00 - 19:15:00 Uhr
header-includes: \setcounter{secnumdepth}{2}

Sitzungsprotokoll FSR Geoinformatik
---
```

should:
```
---
date: 29.04.2020, 18:07:00 - 19:15:00 Uhr
header-includes: \setcounter{secnumdepth}{2}
title: Sitzungsprotokoll FSR Geoinformatik
---
```

**Comment by christophfriedrich** [comment]
oh... \*blush\*
dunno how I couldn't spot that...
thx!
