### ISSUE TITLE
better markdown editor

### ISSUE THREAD

**Issue by noerw** [fs-geofs/Protokollfix#2]
[seems to be a nontrivial task](https://meta.discourse.org/t/syncing-the-editor-viewport-scroll/13249/23)

a scroll map implementation like [this one](564bfa8e) might do.

**Comment by christophfriedrich** [comment]
second link is 404
you meant [this](https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L227-L348)? (link from readme.md)

**Comment by noerw** [comment]
https://github.com/sparksuite/simplemde-markdown-editor
this would look far better and is a simple solution

**Comment by noerw** [comment]
done in 89faecd2168758939a211db0813ce0e84e9010a7
